version: 2

before:
  hooks:
    - go mod download

builds:
  - id: gh-orbit
    binary: gh-orbit
    main: ./cmd/orbit
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - formats: [binary]
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
